# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: BQTO-90_WIN11

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Hola Mundo
      run: echo Hola Mundo!
    
    - name: Run multiple lines
      run: |
        echo Una linea
        echo dos lineas
